#format = '''
#[┌───────────────────>](bold green)
#[│](bold green)$directory$rust$package
#[└─>](bold green) '''

format = """
[](fg:#111314)\
$python\
$username\
[](fg:#111314 bg:#2A2E31)\
$directory\
[](fg:#2A2E31 bg:#00E0FF)\
$git_branch\
$git_status\
[](fg:#00E0FF bg:#FF2FB1)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
[](fg:#FF2FB1 bg:#00FF5E)\
$docker_context\
[](fg:#00FF5E bg:#E6E7E8)\
$time\
[](fg:#E6E7E8)
[└─ ](#FFC845)\
"""
command_timeout = 5000
# Disable the blank line at the start of the prompt
#add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#111314"
style_root = "fg:#FF3B30 bg:#111314"
format = '[$user ]($style)'

[directory]
style = "bg:#2A2E31"
format = "[ $path ]($style)"
truncation_length = 15
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
#"Documents" = "󰈙 "
#"Downloads" = " "
#"Music" = " "
#"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:#FF2FB1"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#00FF5E"
format = '[ $symbol $context ]($style)$path'

[elixir]
symbol = " "
style = "bg:#FF2FB1"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#FF2FB1"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#00E0FF"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#00E0FF"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#FF2FB1"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#FF2FB1"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#FF2FB1"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#FF2FB1"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#FF2FB1"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#FF2FB1"
format = '[ $symbol ($version) ]($style)'

[python]
style = "bg:#584E59"
format = '[(\($virtualenv\) )]($style)'

[rust]
symbol = ""
style = "bg:#FF2FB1"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#E6E7E8 fg:#111314"
format = '[ $time ]($style)'
